### PR TITLE
adding some google owned domains

### PR DESCRIPTION
**Pull request by rmarsollier**
adding the domains of: https://en.wikipedia.org/wiki/List_of_Google_domains

I have a scrapper for this wikipage that extract domains, but this page does not include many domains contained in v2 of google warning list.
Should I push it too in the tools ?

### CODE REVIEW

**Comment by adulau** [comment]
Thank you for the contribution. Could you do  a jq_all_the_things.sh and check the validation? and update the PR. Thanks.

**Comment by adulau** [comment]
Indeed having the scrapper in the tools would be very handy. Thank you.

**Comment by Rafiot** [comment]
(travis is failing because there are duplicates :) )

**Comment by rmarsollier** [comment]
Should work now.

I included a basic scrapper in a separate commit, but it seems there is not every google domain in the wikipedia page(i.e. there was some domain in the previous version of the warning list that does not appear in wikipedia), so it's not really ready yet, we would need to confirm data and merge everything in wikipedia to use it as is.

**Comment by rmarsollier** [comment]
I'll look again into it on Monday.

**Comment by rmarsollier** [comment]
Another PR is coming for this

**Pull request closed without merging**
