### PR TITLE
Added new warninglist for Stackpath CDN

### PR DESCRIPTION
**Pull request by digihash**
I created a new warninglist for the Stackpath CDN (Highwinds before name change of company) and already generated the first list from their website: https://support.stackpath.com/hc/en-us/articles/360001091666-Whitelist-CDN-WAF-IP-Blocks.

### CODE REVIEW

**Comment by digihash** [comment]
I added the new generator in the generate_all.sh script. I don't know what else could cause this test to fail. It just says error 1 but not more information

**Comment by adulau** [comment]
I'll have a look ;-) Thanks a lot for the contribution, it's awesome!

**Comment by adulau** [comment]
FYI, I fixed the IPv6 addresses with the host bit set.

https://github.com/MISP/misp-warninglists/commit/9f426c80993692a7fa56a502699e5d692acd7a4a

Thanks again for the contribution.

**Comment by digihash** [comment]
Great solution, didn't know about this one :)

**Pull request merged**
